spring.application.name=HRMS-Project

server.port=8080

server.servlet.context-path=/

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

spring.datasource.url=jdbc:mysql://localhost:3306/hrms
spring.datasource.username=root
spring.datasource.password=Lunovina@786#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=mySuperSecretKeyThatIsAtLeast32CharactersLong123!

jwt.expiration=60
jwt.refreshExpiration=1440

spring.mail.username=mahankalisandeep90@gmail.com
spring.mail.password=xvab zaux lkrh vdkm

spring.mail.host=smtp.gmail.com
spring.mail.port=587

